apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: scan-dockerfile-task
spec:
  inputs:
    resources: 
    - name: git-source
      type: git
    params:
     - name: Dojo-Product-Name
       description: The Name of the Product in DefectDojo
     - name: Dojo-Engagement-Name
       description: The Name of the Engagement in DefectDojo
  steps:
    - name: dockle-scan
      image: goodwithtech/dockle:v0.4.3
      resources: {}
      workingDir: /workspace/git-source
      script:
        mkdir /dockle
        cd /dockle
        dockle Dockerfile -f json -o /dockle/results.json
    - name: upload-report
      image: pandoraholladay/ddcicd:2
      resources: {}
      workingDir: /workspace/git-source
      script:
         sh ../../DD_Pipeline.sh $(inputs.params.Dojo-Product-Name) $(inputs.params.Dojo-Engagement-Name) ${DD_API_KEY} ${DD_USER} ${DD_URL} /workspace/git-source/dockle dockle
      env:
         - name: DD_API_KEY
           valueFrom:
             secretKeyRef:
               key: dojo-secret.apikey
               name: dojo-secret
         - name: DD_USER
           valueFrom:
             secretKeyRef:
               key: dojo-secret.username
               name: dojo-secret
         - name: DD_URL
           valueFrom:
             configMapKeyRef:
                 name: dojo-configmap
                 key: dojo-configmap.url
