apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: scan-dockerfile-pipeline
spec:
  resources:
    - name: git-source
      type: git
  params:
   - name: Dojo-Product-Name
     description: The Name of the Product in DefectDojo
   - name: Dojo-Engagement-Name
     description: The Name of the Engagement in DefectDojo
  tasks:
  - name: kics-scan-dockerfile-task
    taskRef:
      name: kics-scan-dockerfile-task
      kind: task
    params:
    - name: Dojo-Product-Name
      value: $(params.Dojo-Product-Name)
    - name: Dojo-Engagement-Name
      value: $(params.Dojo-Engagement-Name)
    resources:       
      inputs:
        - name: git-source
          resource: git-source
  - name: checkov-scan-dockerfile-task
    taskRef:
      name: checkov-scan-dockerfile-task
      kind: task
    params:
    - name: Dojo-Product-Name
      value: $(params.Dojo-Product-Name)
    - name: Dojo-Engagement-Name
      value: $(params.Dojo-Engagement-Name)
    resources:       
      inputs:
        - name: git-source
          resource: git-source
