apiVersion: v1
kind: ConfigMap
metadata:
  name: dojo-configmap
  namespace: default
data:
  dojo-configmap.url: https://<release_name>-.apps-crc.testing 
  ## Note by default the <release_name> is set as defectdojo-route, if you wish to change this URL you must update the host value in the DefectDojo chart values.yaml
  ## Note .apps-crc.testing is the external domain you are hosting DefectDojo on, this may be different if you are not using Code ready Containers.
