apiVersion: v1
kind: ConfigMap
metadata:
  name: dojo-configmap
  namespace: default
data:
  dojo-configmap.url: http://<release_name>-defectdojo-django.default.svc.cluster.local ## Note .default.svc.cluster.local is the external domain you are hosting DefectDojo on, this may be different if you are not using Code ready Containers.
