apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: scan-dockerfile-pipeline
spec:
  resources:
    - name: git-source
      type: git
  params:
   - name: Dojo-Product-Name
     description: The Name of the Product in DefectDojo
   - name: Dojo-Engagement-Name
     description: The Name of the Engagement in DefectDojo
   - name: Dojo-Secret-Name
     description: DefectDojo APIKEY 
   - name: Dojo-URL
     description: DefectDojo URL
  resources:
    - name: git-source
      type: git
  tasks:
  - name: scan-dockerfile-task
    taskRef:
      name: scan-dockerfile-task
      kind: task
    params:
    - name: Dojo-Product-Name
      value: $(params.Dojo-Product-Name)
    - name: Dojo-Engagement-Name
      value: $(params.Dojo-Engagement-Name)
    - name: Dojo-Secret-Name
      value: $(params.Dojo-Secret-Name)
    - name: Dojo-URL
      value: $(params.Dojo-URL)
    resources:       
      inputs:
        - name: git-source
          resource: git-source
