apiVersion: tekton.dev/v1beta1 
kind: PipelineRun 
metadata:
  name: scan-dockerfile-pipelinerun-
spec:
  pipelineRef:
    name: scan-dockerfile-pipeline 
  params: 
  - name: Dojo-Product-Name
    value: example_product # Name of the Product to be created in DefectDojo
  - name: Dojo-Engagement-Name
    value: example_enagment # Name of the Engagement to be created in DefectDojo
  - name: Branch_Name
    value: main # Name of the Git repository Branch being scanned
