apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: Scan-Dockerfile-Task
spec:
  params:
   - name: Dojo-Product-Name
     description: The Name of the Product in DefectDojo
   - name: Dojo-Engagement-Name
     description: The Name of the Engagement in DefectDojo
   - name: Dojo-Secret-Name
     description: DefectDojo APIKEY 
   - name: Dojo-URL
     description: DefectDojo URL
  resources:
    inputs:
    - name: git-source
      type: git
tasks:
   name: upload-report
   image: pandoraholladay/DDCICD:1
   resources: {}
   workingDir: workspace/git-source
   script:
      ./DD_Pipeline.sh ${productName} ${engagementName} ${DD_API_KEY} ${DD_USER} ${DD_URL} /workspace/git-source/testDockerfiles/burp burp
