apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: 
spec:
  resources:
    inputs:
    - name: git-source
      type: git
tasks:
   name: upload-report
   image:
   resources: {}
   workingDir: workspace/git-source
   script:
      ./DD_Pipeline.sh ${productName} ${engagementName} ${DD_API_KEY} ${DD_USER} ${DD_URL} /workspace/git-source/NAME NAME
