apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: upload-report-pipeline
spec:
  resources:
    - name: git-source
      type: git
  params:
   - name: Dojo-Product-Name
     description: The Name of the Product in DefectDojo
   - name: Dojo-Engagement-Name
     description: The Name of the Engagement in DefectDojo
   - name: Branch_Name
     description: The Branch Name being scanned
     default: main
  resources:
    - name: git-source
      type: git
  tasks:
  - name: upload-report-task
    taskRef:
      name: upload-report-task
      kind: task
    params:
    - name: Dojo-Product-Name
      value: $(params.Dojo-Product-Name)
    - name: Dojo-Engagement-Name
      value: $(params.Dojo-Engagement-Name)
    - name: Branch_Name
      value:  $(params.Branch_Name)
    resources:       
      inputs:
        - name: git-source
          resource: git-source
