apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: pipeline-trigger
      interceptors:
       - cel:
           filter: "body.commits.modified[0] == 'Dockerfile' || body.commits.added[0] == 'Dockerfile' || body.commits[0].message == 'Update Dockerfile'"
           overlays:
           - key: timestamp
             expression: "body.commits[0].timestamp.truncate(10)"
           - key: giturl
             expression: "body.repository.original_url"
           - key: gitrevision
             expression: "body.ref.split('/')[2]"
             # Use below overlay instead if mirroring a repository in Gitea
   #        - key: gitrevision
   #         expression: "body.ref"
      bindings:
        - kind: TriggerBinding
        - ref: pipeline-trigger-binding
      template:
        ref: pipeline-template
