apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: pipeline-trigger
      interceptors:
       - cel:
           filter: "body.commits.modified[0] == 'Dockerfile' || body.commits.added[0] == 'Dockerfile' || body.commits.message == 'Dockerfile'"
           overlays:
           - key: extensions.timestamp
             expression: "body.commits.timestamp.truncate(10)"
           - key: extensions.giturl
             expression: "body.repository.url"
           - key: extensions.branch_name
             expression: "body.ref.split('/')[2]"
      bindings:
        - ref: pipeline-trigger-binding
      template:
        ref: pipeline-template
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: Route
metadata:
  name: el-route
spec:
  host: eventlistener-route.apps-crc.testing
  to: 
    kind: Service
    name: el-listener
