apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: pipeline-trigger
      interceptors:
       - cel:
           filter: "body.commits.modified[0] == 'Dockerfile' || body.commits.added[0] == 'Dockerfile' || body.commits[0].message == 'Update Dockerfile'"
           overlays:
           - key: extensions.timestamp
             expression: "body.commits[0].timestamp.truncate(10)"
           - key: extensions.giturl
             expression: "body.repository.original_url"
           - key: extensions.branch_name
             expression: "body.ref.split('/')[2]"
      bindings:
        - ref: pipeline-trigger-binding
      template:
        ref: pipeline-template
