apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: pipeline-trigger
      interceptors:
       - cel:
           filter: "body.commits.modified[0] == 'Dockerfile' || body.commits.added[0] == 'Dockerfile' || body.commits[0].message == 'Update Dockerfile'"
           overlays:
           - key: timestamp
             expression: "body.commits[0].timestamp.truncate(10)"
           - key: giturl
             expression: "body.repository.original_url"
           - key: branch_name
             expression: "body.ref.split('/')[2]"
      bindings:
        - kind: TriggerBinding
        - ref: pipeline-trigger-binding
        - kind: TriggerBinding
          name: timestamp
          value: $(extensions.timestamp)
        - kind: TriggerBinding
          name: giturl
          value: $(extensions.giturl)
        - kind: TriggerBinding
          name: branch_name
          value: $(extensions.branch_name)
      template:
        ref: pipeline-template
