apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-trigger-binding
spec:
  params:
  - name: gitrevision
    value: $(extensions.branch_name)
  - name: timestamp
    value: $(extensions.timestamp)
  - name: giturl
    value: $(extensions.giturl)
