apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
  namespace: default
spec:
  params:
  - name: git-revision
    description: The git revision
    default: main
  - name: git-repository-url
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: content-type
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: scan-dockerfile-pipeline-run-
    spec:
      pipelineRef:
        name: scan-dockerfile-pipeline
      params:
      - name: message
        value: $(tt.params.message)
      - name: contenttype
        value: $(tt.params.contenttype)
      resources:
      - name: git-source
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(tt.params.gitrevision)
          - name: url
            value: $(tt.params.gitrepositoryurl)
