apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-trigger-binding
spec:
  params:
  - name: gitrevision
    value: $(extensions.gitrevision)
  - name: timestamp
    value: $(extensions.committimestamp)
  - name: url
    value: $(extensions.giturl)

