apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
  namespace: default
spec:
  params:
  - name: git-revision
    description: The git revision
    default: main
  - name: git-repository-url
    description: The git repository url
  - name: commmit-timestamp
    description: The timestamp of the commit
  - name: Dojo-Product-Name
    description: The Name of the Product in DefectDojo
  - name: Dojo-Engagement-Name
    description: The Name of the Engagement in DefectDojo
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: scan-dockerfile-pipeline-run-
    spec:
      pipelineRef:
        name: scan-dockerfile-pipeline
      params:
      - name: timestamp
        value: $(tt.params.committimestamp)
      - name: Dojo-Product-Name
        value: Sprint-$(tt.params.gitrevision)
      - name: Dojo-Engagement-Name
        value: Scan-$(tt.params.committimestamp)
      resources:
      - name: git-source
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(tt.params.gitrevision)
          - name: url
            value: $(tt.params.gitrepositoryurl)
