apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: kics-scan-dockerfile-task
spec:
  inputs:
    resources: 
    - name: git-source
      type: git
    params:
     - name: Dojo-Product-Name
       description: The Name of the Product in DefectDojo
     - name: Dojo-Engagement-Name
       description: The Name of the Engagement in DefectDojo
  steps:
    - name: kics-report
      image: checkmarx/kics:latest
      resources: {}
      workingDir: /workspace/git-source
      script:
       mkdir kics
       
       cd kics
       
       kics scan -p /workspace/git-source/Dockerfile --ignore-on-exit all -s -o /workspace/git-source/kics/results.json
    - name: upload-report
      image: pandoraholladay/ddcicd:5
      imagePullPolicy: Always
      resources: {}
      workingDir: /workspace/git-source
      script: 
       cd /defectdojo_api/
      
       python dojo_ci_cd.py --host ${DD_URL} --user ${DD_USER} --api_token ${DD_API_KEY} --product_name $(inputs.params.Dojo-Product-Name) --engagement_name $(inputs.params.Dojo-Engagement-Name) --dir /workspace/git-source/kics --scanner kics
      env:
         - name: DD_API_KEY
           valueFrom:
             secretKeyRef:
               key: dojo-secret.apikey
               name: dojo-secret
         - name: DD_USER
           valueFrom:
             secretKeyRef:
               key: dojo-secret.username
               name: dojo-secret
         - name: DD_URL
           valueFrom:
             configMapKeyRef:
                 name: dojo-configmap
                 key: dojo-configmap.url
