{{- if .Values.route.enabled -}}
{{- $fullName := include "gitea.fullname" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: {{ $httpPort }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: { $fullName }}-http
    weight: 100
  wildcardPolicy: None
{{- end }}
